### ISSUE TITLE
eb-clock: missing libm 

### ISSUE THREAD

**Issue by qermit** [GSI-CS-CO/bel_projects#1]
* snapshot_180116 7ae4c8b submodules: use correct etherbone library location

`gcc  -Wall -O2 -I /root/bel_projects/ip_cores/etherbone-core/api -I /root/bel_projects/ip_cores/wr-cores/modules/wr_eca -I /root/bel_projects/ip_cores/wr-cores/modules/wr_tlu -o eb-clock eb-clock.c -L /root/bel_projects/ip_cores/etherbone-core/api/.libs -L /root/bel_projects/ip_cores/wr-cores/modules/wr_eca -L /root/bel_projects/ip_cores/wr-cores/modules/wr_tlu -Wl,-rpath,/usr/local/lib -letherbone -leca -ltlu
/usr/bin/ld: /tmp/ccd65foJ.o: undefined reference to symbol 'floor@@GLIBC_2.2.5'
/usr/bin/ld: note: 'floor@@GLIBC_2.2.5' is defined in DSO /lib64/libm.so.6 so try adding it to the linker command line
/lib64/libm.so.6: could not read symbols: Invalid operation
`

`gcc  -Wall -O2 -I /root/bel_projects/ip_cores/etherbone-core/api -I /root/bel_projects/ip_cores/wr-cores/modules/wr_eca -I /root/bel_projects/ip_cores/wr-cores/modules/wr_tlu -o eb-clock eb-clock.c -L /root/bel_projects/ip_cores/etherbone-core/api/.libs -L /root/bel_projects/ip_cores/wr-cores/modules/wr_eca -L /root/bel_projects/ip_cores/wr-cores/modules/wr_tlu -Wl,-rpath,/usr/local/lib -letherbone -leca -ltlu -lm
make[1]: Leaving directory `/root/bel_projects/tools'`

**Comment by alex-cscotg** [comment]
Fixed in proposed_master.
