### ISSUE TITLE
[Balloon] eca tools in standard build

### ISSUE THREAD

**Issue by dietrichb** [GSI-CS-CO/bel_projects#10]
When building the project, using "make" without using any other parameters will also build the eca tools.

Those eca tools are intended for use with the old ECA1, but "balloon" is a release focused around the new ECA2.

Suggest to remove "eca" from the list of default components.

**Comment by alex-cscotg** [comment]
Maybe we should also remove the "tlu" tools? I'm not sure if EE is still using this component.

Latching inputs can be done via ECAv2 as well.

**Comment by dietrichb** [comment]
I think I cleaned this up. See branch "tools_dietrich-2016-11-11"

**Comment by alex-cscotg** [comment]
Looks fine and works for me.

Should this be merged into balloon (or into our next release)? @bradomyn

**Comment by dietrichb** [comment]
Not yet. Still fixing some other things.

**Comment by dietrichb** [comment]
Done. Waiting for merge into balloon --> https://github.com/GSI-CS-CO/bel_projects/pull/12

**Comment by alex-cscotg** [comment]
Done.
