### ISSUE TITLE
[Balloon] no real "clean" when using make (here: etherbone)

### ISSUE THREAD

**Issue by dietrichb** [GSI-CS-CO/bel_projects#11]
The build procedure for etherbone has been migrated to autoconf tools. Within this procedure, "Makefile" is autogenerated.

A "make clean" or "make distclean" does not really work. Even binaries and object files are not deleted.  Also the generated Makefile is not removed.

The only workaround is "git clean -xfd ." for all submodules within the repo (or delete the local copy of the repo and create a new one).

**Comment by alex-cscotg** [comment]
Fixed.
