### ISSUE TITLE
'make' for etherbone partly broken

### ISSUE THREAD

**Issue by dietrichb** [GSI-CS-CO/bel_projects#110]
This happens after a fresh clone/checkout of doomsday branch on a freshly installed ubuntu beaver box.

'eb-ls' throws error 'eb-ls: error while loading shared libraries: libetherbone.so.5: cannot open shared object file: No such file or directory' 

Everything is built and installed in standard path /usr/local

Please note: EB "tools" (eb-flash ...) work fine after building and installing. Just "native" EB binaries of 'etherbone' itself fail to execute (using the LD_LIBRARY_PATH hack works of course).

**Comment by alex-cscotg** [comment]
OS: Ubuntu 18

**Comment by dietrichb** [comment]
August 2019: can't reprode -> closed
