### ISSUE TITLE
WR port not reachable after power cycle of WR switch

### ISSUE THREAD

**Issue by dietrichb** [GSI-CS-CO/bel_projects#111]

**Comment by dietrichb** [comment]
symptoms
========
WRS
- ports shows MAC and ptp state 6 (looks good)

node 
- eb-mon shows LINK_UP and TRACKING (looks good)
- node not reachable via timing network (all EB requests time out)

when
====
- after reboot power cycle of WRS
- it may take a few power cycles of the WRS to trigger the bug

workaround
=========
power cycle or restart FPGA using eb-reset

**Comment by dietrichb** [comment]
solved for Arria5 based platforms

requires major work (PHY control update) for Arria II based devices (SCU and VETAR)

**Comment by alexazon** [comment]
See #309
