### ISSUE TITLE
eb-info and eb-flash: irritating command line help

### ISSUE THREAD

**Issue by dietrichb** [GSI-CS-CO/bel_projects#13]
[ruth@FEC ~]# eb-info 
eb-info: expecting three non-optional arguments: <proto/host/port>
[ruth@FEC ~]# eb-flash
eb-flash: expecting three non-optional arguments: <proto/host/port> <firmware>

The number given for the non-optional arguments is wrong. The tools expect one or two arguments, not three. Shall I fix this?

**Comment by alex-cscotg** [comment]
Sure, fix it :+1:

**Comment by dietrichb** [comment]
Should be fixed in branch dietrich_eb-tools_22-11-2016 --> Pull request.

Please close this issue after successful merge,
