### ISSUE TITLE
connecting a TR via USB does not work on SCU

### ISSUE THREAD

**Issue by dietrichb** [GSI-CS-CO/bel_projects#136]
I did not manage to connect a TR via USB to a PC with SCU image. The /dev/ttyUSB0 (or similar) does not show up.

 dmesg yields:
[ 1335.131557] hub 3-0:1.0: state 7 ports 15 chg 0000 evt 0200
[ 1335.131572] hub 3-0:1.0: port 9, status 0101, change 0001, 12 Mb/s
[ 1335.235192] hub 3-0:1.0: debounce: port 9: total 100ms stable 100ms status 0x101
[ 1335.286167] hub 3-0:1.0: port 9 not reset yet, waiting 50ms
[ 1335.388153] usb 3-9: new high-speed USB device number 2 using xhci_hcd
[ 1335.400074] usb 3-9: skipped 4 descriptors after interface
[ 1335.400206] usb 3-9: default language 0x0045
[ 1335.401357] usb 3-9: udev 2, busnum 3, minor = 257
[ 1335.401361] usb 3-9: New USB device found, idVendor=1d50, idProduct=6062
[ 1335.401896] usb 3-9: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 1335.402427] usb 3-9: Product: USB-{Serial,Wishbone} adapter
[ 1335.402940] usb 3-9: Manufacturer: GSI Helmholtzzentrum
[ 1335.403577] usb 3-9: usb_probe_device
[ 1335.403579] usb 3-9: configuration #1 chosen from 1 choice
[ 1335.403745] usb 3-9: Successful Endpoint Configure command
[ 1335.403790] usb 3-9: adding 3-9:1.0 (config #1, interface 0)
[ 1335.404373] usb 3-9: adding 3-9:1.1 (config #1, interface 1)
[ 1335.404946] usb 3-9: adding 3-9:1.2 (config #1, interface 2)

trying to force the driver manually yields:

command line:
[ruth@node ~]# insmod wishbone-serial.ko 
insmod: can't insert 'wishbone-serial.ko': unknown symbol in module or invalid parameter

dmesg: 
[ 1490.105166] wishbone_serial: Unknown symbol usb_serial_generic_open (err 0)
[ 1490.105688] wishbone_serial: Unknown symbol usb_serial_generic_close (err 0)
[ 1490.106221] wishbone_serial: Unknown symbol usb_serial_deregister_drivers (err 0)
[ 1490.106725] wishbone_serial: Unknown symbol usb_serial_register_drivers (err 0)

cat /etc/timing-rte_buildinfo yields:

GSI Timing RTE 08-06-2018_13-14-43 
Compiled by ahahn using ./build-rte.sh on asl742.acc.gsi.de - Linux  3.10.0-862.2.3.el7.x86_64
CI_CD Project
 - https://github.com/GSI-CS-CO/ci_cd.git
 -  master*@bf0c466
BEL_PROJECTS
 - https://github.com/GSI-CS-CO/bel_projects.git
 - doomsday-v4.0.5@23f29bb
Last Commits in repo:
23f29bb fpga-config-space: added pmc/pci support
02ca0d4 saftlib: v1.4.1
e13be6a Merge pull request #95 from GSI-CS-CO/scu_dreq_clear
d80f22d Merge pull request #94 from GSI-CS-CO/eb-tools_dietrich_2018-may-04
bc2be39 scu_sw: send broadcast only to active sios

**Comment by alex-cscotg** [comment]
Fixed (2001aa2@ci_cd)
