### ISSUE TITLE
eb-massmon (warning)

### ISSUE THREAD

**Issue by alex-cscotg** [GSI-CS-CO/bel_projects#146]
eb-massmon.c: In function ‘main’:
eb-massmon.c:784:32: warning: ‘.’ directive writing 1 byte into a region of size between 0 and 1024 [-Wformat-overflow=]
         sprintf(devName, "%s/%s.%s", ebProto, node, domain);
                                ^
eb-massmon.c:784:9: note: ‘sprintf’ output 3 or more bytes (assuming 1027) into a destination of size 1025
         sprintf(devName, "%s/%s.%s", ebProto, node, domain);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

gcc:
gcc (GCC) 8.3.1 20190223 (Red Hat 8.3.1-2)

**Comment by dietrichb** [comment]
can't reproduce this with gcc 7.4  -> postponed

**Comment by alex-cscotg** [comment]
Out of date
/closed
