### ISSUE TITLE
etherbone dissector with standard installation (~ ubuntu bionic)

### ISSUE THREAD

**Issue by dietrichb** [GSI-CS-CO/bel_projects#178]
After defining 'etherbone.lua' in 'init.lua', wireshark reports the following error message:

"Lua: Error during loading:
 /SOMEPATH/etherbone.lua:57: bad argument #3 to 'bytes' (Display must be either base.NONE, base.DOT, base.DASH, base.COLON or base.SPACE)"

This can be fixed by replacing three occurrences of the statement

"ProtoField.bytes("eb.rec", ..., base.HEX)"

by 

"ProtoField.bytes("eb.rec", ..., base.NONE)

(see https://www-acc.gsi.de/wiki/Timing/TimingSystemEBWireshark)

**Comment by alexazon** [comment]
Fixed, see etherbone-core v.2.1.3.
