### ISSUE TITLE
Big offset between WR and ECA PPS

### ISSUE THREAD

**Issue by bradomyn** [GSI-CS-CO/bel_projects#18]
we have observed a big offset between the PSSs of WR and the ones triggered by ECA, around 200ns
It is clear that the ECA need some time to process the events, but what we see, is it normal?

Alex's theory is that we have increased the output delay of the ECA when we have fixed timing violations problems reducing the fan-out... 

For Release 10 we should check:
- delay in ECA
- differences in the output delay increasing the fan-out

**Comment by alex-cscotg** [comment]
If I remember correctly we saw 30ns between ECA PPS and WR PPS and 200ns between Switch and nodes?
I will check this again.

**Comment by alex-cscotg** [comment]
Okay I measured it again:

Node PPS WR vs Switch: ~110ns
Node PPS ECA vs Switch: ~ 140ns
Node PPS ECA vs Node PPS  WR: ~ 30ns

ECA -> WR -> Switch (ECA PPS comes first, Switch PPS comes last)

**Comment by bradomyn** [comment]
my bad, sorry.

Thanks for the measurements

**Comment by alex-cscotg** [comment]
Out-dated -> Closed.
