### ISSUE TITLE
connection between White Rabbbit node and switch unreliable after reboot of WRS

### ISSUE THREAD

**Issue by dietrichb** [GSI-CS-CO/bel_projects#265]
a variety of symptoms is observed when rebooting a WRS to which is WR node is connected. This can happen during maintenance, WRS reboot on purpose, or when recovering from a power-cut.

1. no White Rabbit lock, occasionally; WRS port claims WA_MSG (waiting for message); node is accessible via the network
2. no Ethernet link; rarely; WRS ports claims 'link down'; node inaccessible
3. 'hang up'; WRS port claims 'WA_MSG' and node MAC is detected by the WRS; node inaccessible via the network

In all cases, power-cycling the WR node helps
In cases '1' and '2' it is usually possible to recover by 'eb-reset' of the node. 
In case '1', forcing a sequence port up->down->up on the WRS helps in some cases
In case '2', forcing a sequence port up->down->up on the WRS does not help
In case '3', the node seems to be almost dead. Access to the node is possible neither from the timing network nor from the host system (no chance for eb-reset). Forcing port ->down->up on the WRS does not help. Autorecovery of the WR node via the 'watchdog' implemented on the SCU does not work. A powercycle helps.

**Comment by alexazon** [comment]
See #309
