### ISSUE TITLE
WR node hangs in endless BOOTP loop, when WR PTP link is not established

### ISSUE THREAD

**Issue by dietrichb** [GSI-CS-CO/bel_projects#266]
In rare cases it might happen that a WR node is unable to establish a WR PTP link. In this case the following symptoms are commonly observed.

- node issues a BOOTP request via the network ~once every second
- (BOOTP server replies with IP)
- when reading the relevant register of the WR core, the IP matches the one from the BOOTP server reply: it seems the reply from the BOOTP server has been received by the node
- (I believer the console claims 'in training' for IP)
- the node continues issuing BOOTP requests until the WR PTP link is successfully established

I am not sure if this is an issue with the way how the WR core is instantiated on Arria II devices or of this is an issue of the WR core itself. Should we file this issue on OHWR?

**Comment by alexazon** [comment]
See #309
