### ISSUE TITLE
PEXARIA: t0 serial time stamp LVDS polarity

### ISSUE THREAD

**Issue by jamusch** [GSI-CS-CO/bel_projects#27]
The PEXARIA LVDS output of t0 with serial time stamp has wrong polarity for BALLOON release
(tested by Nikolaus Kurz).
**Note:** A  bitfile with a working fix has been generated by Alexander Hahn, this correction should be put into next release branch.

**Comment by alex-cscotg** [comment]
@bradomyn: Should we create a patch for balloon or put that into the "C" release?

**Comment by alex-cscotg** [comment]
Fixed by pull request #24.
