### ISSUE TITLE
VETAR: interrupts with multiple cards do not always work

### ISSUE THREAD

**Issue by miree** [GSI-CS-CO/bel_projects#30]
In one VME crate (ELMA Type 39 Horizontal, borrowed from beam diagnostics group) up to 3 Vetar cards have been working. All are accessible via eb-tools and all recieve interrupts (saft-ctl snoop ... works). In other crates, e.g. the one in the testing facility (from WIENER), the interrupts do work only occasionally on all cards. Sometimes only two of the cards are getting interrupts. Most of the time only one card gets interrupts.

**Comment by alex-cscotg** [comment]
As far as I know this was fixed by commit 4969f2027578683f7f5eff02cf92434b109c6403.

@miree : Please confirm that.

**Comment by miree** [comment]
confirmed
