### ISSUE TITLE
eb-X fails in 32bit machines

### ISSUE THREAD

**Issue by bradomyn** [GSI-CS-CO/bel_projects#4]
The Icinga monitoring of the Testing Facility  tsl006 (32bits) shows that the nodes:
expl011t
scuxl0001t
are not answering regularly (3 times out of 10 fails) to the etherbone commands eb-track or eb-datum . Basically this commands read a register of the wr-core and the error message is:
`eb-info: eb_sdb_find_by_identity: one or more operations failed`

Using the same network, switches etc... we have tested the eb-track or eb-datum  commands and work perfectly.

The first idea is that Etherbone has a problem on 32 bit platforms

**Comment by alex-cscotg** [comment]
There are no more 32bit machines which use some eb-tools.
Am also unable to reproduce this.

Closed
