### ISSUE TITLE
eb-flash does not work for vetar2a (with default parameters)

### ISSUE THREAD

**Issue by miree** [GSI-CS-CO/bel_projects#42]
As workaround, one can use eb-flash with command line option "-w 3". 
e.g.: eb-flash -w 3 dev/wbm0 vetar2a.rpd

**Comment by miree** [comment]
the proposed workaround doesn't work on EE Linux systems. the eb-flash tool does not accept the "-w 3" parameter !?

**Comment by alex-cscotg** [comment]
Fixed with cherry/doomsday.

Closed.
