### ISSUE TITLE
Tool: eb-mon shows in rare cases incorrect one-wire ID's ( verified by checksum calculation)

### ISSUE THREAD

**Issue by klkaiser** [GSI-CS-CO/bel_projects#49]
Bugfix Priority: "lower priority"

SCU Timing Receiver Functional Test uses eb-mon from bel_projects tools for read-out of 1W IDs.
Occasionally the first 8 bits of these 1W IDs are nulled (which is wrong).
We have verified all 1W IDs with below shown Checksum algorithm (which works well for correct
1W IDs):
...................................................................................................................................................................................................................
Function CheckOneWireCRC(ByRef OneWireID As String, ByRef strDelimiter As String) As Variant
Dim InHex, OutBinStr As String
Dim OutBinArr(1 To 56) As Integer
Dim iRefDec, i, CRC(1 To 8), CRCTemp As Integer
    
    On Error GoTo err_exit
    'Application.Volatile
    
    If Len(strDelimiter) <> 0 And Len(strDelimiter) = 1 Then
        InHex = Replace(OneWireID, strDelimiter, "")
    Else
        InHex = OneWireID
    End If
    ' die enthaltene CRC
    iRefDec = Val("&H" & Left(InHex, 2))
    InHex = Right(InHex, Len(InHex) - 2)

    If Len(InHex) < 14 Then
err_exit:
        CheckOneWireCRC = CVErr(xlErrValue)

        On Error GoTo 0
    Else
        OutBinStr = HexToBin(InHex)
        ' Convert string to array, LSB = OutBinArr(1)
        For i = 1 To 56
            OutBinArr(57 - i) = Mid$(OutBinStr, i, 1) ' Split(OutBinStr)
        Next i
        
        'Initialize CRC
        For i = 1 To 8
            CRC(i) = 0
        Next i
        
        'Calculate CRC
        For i = 1 To 56
            CRCTemp = CRC(1) Xor OutBinArr(i)
            CRC(1) = CRC(2)
            CRC(2) = CRC(3)
            CRC(3) = CRC(4) Xor CRCTemp
            CRC(4) = CRC(5) Xor CRCTemp
            CRC(5) = CRC(6)
            CRC(6) = CRC(7)
            CRC(7) = CRC(8)
            CRC(8) = CRCTemp
        Next i
        
        CRCTemp = BinToDec(CRC)
        If CRCTemp <> iRefDec Then
            CheckOneWireCRC = False
        Else
            CheckOneWireCRC = True
        End If
    End If
End Function

**Comment by dietrichb** [comment]
will be fixed with "D" release
