### ISSUE TITLE
legacy-vme64x-core folder empty on cloning

### ISSUE THREAD

**Issue by dslavineccsl** [GSI-CS-CO/bel_projects#5]
Hi,

When I clone bel_projects and then submodule init and update, folder
/ip_cores/fpga-config-space/legacy-vme64x-core

is empty. It is also empty, when I run deployment scritp.

**Comment by alex-cscotg** [comment]
cd ip_cores/fpga-config-space
git submodule init
git submodule update --recursive

**Comment by alex-cscotg** [comment]
Works!
