### ISSUE TITLE
eb-flash sometimes fails due to wrongly reported sector size

### ISSUE THREAD

**Issue by dietrichb** [GSI-CS-CO/bel_projects#76]
Flashing a devices fails, if the device is reporting a wrong sector size to the eb-flash tool. 

If this happens, a wrong sector size of 0x100 is reported. Then, flashing the device takes really long (hours!) and might result in a bricked device.

As a temporary workaround, a ugly hack has been added to the eb-flash tool ( https://github.com/GSI-CS-CO/bel_projects/commit/9b74673f61b3e4ec06a71109891b87a987c9235f )

**Comment by alex-cscotg** [comment]
Depends/varies on synthesis.

Fixed with current doomsday release.

ToDo: Fix flash controller

See also:
https://github.com/GSI-CS-CO/bel_projects/issues/83
https://github.com/GSI-CS-CO/bel_projects/issues/82
