### ISSUE TITLE
eb-flash on scu2/3 (doomsday) - verify failed at address 0x21000104 (0x1 != 0xffffffff)

### ISSUE THREAD

**Issue by alexazon** [GSI-CS-CO/bel_projects#82]
I observed this:

- Sometimes the first attempt to flash a SCU over PCIe will fail
- The second attempt will (always?) work
- Every attempt to flash over UDP will succeed

[root@scuxl0150 ~]# killall saftd
[root@scuxl0150 ~]# eb-flash dev/wbm0 scu3.rpd 
Autodetecting sector size: found = 0x40000         
Scanning offset 0x21ffff44 ... done!
Erasing 0x21fc0000 ... done!
Programming 0x21ff0000... done!
Verifying 0x21000000... eb-flash: verify failed at address 0x21000104 (0x1 != 0xffffffff)

[root@scuxl0150 ~]# eb-flash dev/wbm0 scu3.rpd 
Autodetecting sector size: found = 0x40000         
Scanning offset 0x21ffff44 ... done!
Erasing 0x21fc0000 ... done!
Programming 0x21ff0000... done!
Verifying 0x21ff0000... done!

[root@scuxl0150 ~]# eb-info dev/wbm0
Project     : scu_control
Platform    : scu3 +comexpress
FPGA model  : Arria II GX (ep2agx125ef29c5)
Source info : doomsday-1904
Build type  : Doomsday-v4.0.4
Build date  : Tue Apr 17 14:02:40 CEST 2018
Prepared by : Jenkins Nightly Build <csco-tg@gsi.de>
Prepared on : tsl002.acc.gsi.de
OS version  : Debian GNU/Linux 8.10 (jessie), kernel 3.16.0-4-amd64
Quartus     : Version 16.0.0 Build 211 04/27/2016 SJ Standard Edition

  14ffc1a install-hdlmake: fixed installation
  2fe7692 wrpc-sw: removed syslog spam
  cc0dc49 pmc: set OPTIMIZATION_MODE to HIGH PERFORMANCE EFFORT
  f6e583f pexarria5: set OPTIMIZATION_MODE to HIGH PERFORMANCE EFFORT
  21849c4 exploder5: set OPTIMIZATION_MODE to HIGH PERFORMANCE EFFORT

**Comment by dietrichb** [comment]
workaround: use eb-flash-secure

**Comment by alexazon** [comment]
- Use eb-flash-secure
- Our next major release will contain a new flash controller (ASMI)
