### ISSUE TITLE
eb-flash on scu2/3 (doomsday) stalls complete OS on host and fpga 

### ISSUE THREAD

**Issue by alexazon** [GSI-CS-CO/bel_projects#83]
This issue has to be fixed inside the flash controller

Observation: Sometimes a bad combination of ECPU settings and LM32-User code causes a breakdown of the SCU (host and fpga) 

Reason: LM32 keeps polling the ECA ECPU channel and delays the access to the flash controller, the wishbone signals (from flash) stall the whole wishbone bus

Workaround: Stop the (user) LM32s (additional: kill saftlib and all fesa apps) before flashing

Example:

$ eb-ls dev/ttyUSB0 | grep FPGA_RESET
12.5           0000000000000651:3a362063           4000010  FPGA_RESE
$ eb-write dev/ttyUSB0 0x4000018/4 0x1       // add 0x8
$ eb-flash ...
$ eb-reset ...

0x18 = Stop register
0x1c = Start register

**Comment by dietrichb** [comment]
please use eb-flash-secure (this just makes the symptom go away)
